embeetle_dry_run: \
project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_crc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sai_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma2d.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dac.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spdifrx.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_lptim.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dfsdm.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_i2c.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_wwdg.c.o \
  project/source/user_code/main.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_tim.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smbus.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cec.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpsmbus_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c.o \
  project/source/startup_stm32f407xx.s.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_smartcard.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_spi.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmpi2c.c.o \
  project/source/user_code/stm32f4xx_hal_msp.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_irda.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_qspi.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c.o \
  project/source/user_code/system_stm32f4xx.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_lptim.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rng.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c.o \
  project/source/user_code/stm32f4xx_it.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dac.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c.o \
  project/source/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c.o